readr/author/urls.py
from django.urls import path

from . import views


app_name = 'author'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('<int:pk>/', views.detail, name='detail'),
]

readr/book/urls.py
from django.urls import path

from . import views


app_name = 'book'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

readr/core/urls.py
from django.urls import  path,include
from . import views

from django.views.generic.base import TemplateView

app_name = 'core'

urlpatterns = [
    path('',views.index, name='index'),
    
    # authentication forms
    path('register/',views.register, name='register'),

    path('login/',views.login, name='login'),
    path('logout',views.logout, name="logout"),
]

readr/readr/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('author/', include('author.urls',namespace= 'author')),
    path('books/', include('book.urls',namespace= 'books')),
    
    
    
    path('admin/', admin.site.urls),
    path('core/',include('django.contrib.auth.urls')),
    path('core/',include('core.urls',namespace= 'core')),
    path('',TemplateView.as_view(template_name = "core/home.html"), name="home"),
   
    
    
]

readr/author/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    # Fields for the Author model
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(blank=True, null=True)

    
    def __str__(self) -> str:
        return self.first_name  + " " + self.last_name

readr/book/models.py
from django.db import models
from author.models import Author


class Book(models.Model):
    WANTED = 'wanted'
    WAITING = 'waiting'
    READING = 'reading'
    READ = 'read'

    STATUS_CHOICES = (
        (WANTED, 'Wanted'),
        (WAITING, 'Waiting'),
        (READING, 'Reading'),
        (READ, 'Read')
    )

    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, related_name='books', on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=WAITING)

    class Meta:
        ordering = ('title',)

readr/core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class User(models.Model):
    username = models.CharField(max_length=259)
    password = models.CharField

readr/author/forms.py
from django.forms import ModelForm
from .models import Author

class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['first_name','last_name','date_of_birth',]

readr/book/forms.py
from django.forms import ModelForm

from .models import Book


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'status',)

readr/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import PasswordInput,TextInput
from django.contrib.auth.forms import AuthenticationForm



class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password']


class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username','email', 'password1', 'password2']




    
    

readr/author/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import AuthorForm
from .models import Author


def index(request):
    authors = Author.objects.all()

    return render(request, 'author/index.html', {
        'authors': authors
    })


def detail(request, pk):
    author = get_object_or_404(Author, pk=pk)

    return render(request, 'author/detail.html', {
        'author': author
    })


def add(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('author:index')
    else:
        form = AuthorForm()

    return render(request, 'author/add.html', {
        'form': form
    })

readr/book/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import BookForm
from .models import Book


def index(request):
    books = Book.objects.all()

    return render(request, 'book/index.html', {
        'books': books
    })


def detail(request, pk):
    book = get_object_or_404(Book, pk=pk)

    return render(request, 'book/detail.html', {
        'book': book
    })


def add(request):
    if request.method == 'POST':
        form = BookForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('book:index')
    else:
        form = BookForm()

    return render(request, 'book/add.html', {
        'form': form
    })


def edit(request, pk):
    book = get_object_or_404(Book, pk=pk)

    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)

        if form.is_valid():
            form.save()

            return redirect('book:index')
    else:
        form = BookForm(instance=book)
    
    return render(request, 'book/edit.html', {
        'form': form
    })


def delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    book.delete()

    return redirect('book:index')

readr/core/views.py
from django.shortcuts import render,redirect
from django.urls import reverse,reverse_lazy
from .forms import  SignUpForm, LoginForm
from django.contrib import messages
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required





# Create your views here.
def  index(request):
    return render(request, 'core/index.html')

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request.POST)
        if form.is_valid(): 
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = authenticate(request,username=username,password=password)     
            if user is not None:
                login(request,user)
                messages.success(request,f"You logged in as {username} ")
                return redirect('index')
            else:
                messages.error(request,"Invalid username or password")
                return redirect('login')           
        else:
            messages.error(request,f"Some problem encountered")
            return redirect('login')        
    else:
        form = AuthenticationForm()
        return render(request, 'registration/login.html',context={"form":form})

    
def logout(request):
        logout(request)
        messages.success(request,f"You have logged out ")
        return  redirect('login') 

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('login') 
    else:
        form=UserCreationForm()
        context = {'form': form}
    return render (request,"registration/register.html",context)















    



 

readr/author/templates/author/add.html
{% extends 'core/base.html' %}

{% block title %}Add author{% endblock %}

{% block content %}
    <h1 class="text-2xl">Add author</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-4 px-6 bg-sky-700 text-white">Submit</button>
    </form>
{% endblock %}

readr/author/templates/author/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ author.last_name }}{% endblock %}

{% block content %}
    <h1 class="mb-6 text-2xl">{{author.first_name}} {{ author.last_name }} </h1>
    
    <hr>
    <br>
    
        

    <a href="{% url 'book:add' %}" class="mb-6 py-4 px-6 inline-block bg-sky-700 text-white">Add book</a>    
    <!-- <button class="py-4 px-6 bg-sky-700 text-white">Add book</button> -->
    
    {% if author.books.count %}
        {% for book in author.books.all %}
            <div class="p-4 grid grid-cols-2 gap-4 bg-slate-100">
                <h2>
                    <a href="{% url 'book:detail' book.id %}">{{ book.title }}</a>
                </h2>
                <p>{{ book.get_status_display }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p>This author doesn't have any books yet...</p>
    {% endif %}
    
{% endblock %}

readr/author/templates/author/index.html
{% extends 'core/base.html' %}

{% block title %}Authors{% endblock %}

{% block content %}
    <h1 class="mb-6 text-2xl">Authors</h1>

    <a href="{% url 'author:add' %}" class="mb-6 py-4 px-6 inline-block bg-sky-700 text-white">Add author</a>
    
    <div class="space-y-4">
        {% for author in authors %}
            <div class="py-4 px-6 bg-slate-100">
                <a href="{% url 'author:detail' author.id %}">{{ author.last_name }}</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

readr/book/templates/book/add.html
{% extends 'core/base.html' %}

{% block title %}Add book{% endblock %}

{% block content %}
    <h1 class="text-2xl">Add book</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-4 px-6 bg-sky-700 text-white">Submit</button>
    </form>
{% endblock %}

readr/book/templates/book/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ book.title }}{% endblock %}

{% block content %}
    <h1 class="mb-6 text-2xl">{{ book.title }}</h1>

    <h3><strong>Status:</strong> {{ book.get_status_display }}</h3>
    <h3><strong>Author:</strong> <a href="{% url 'author:detail' book.author.id %}">{{ book.author.first_name }} {{ book.author.last_name }}</a></h3>

    <a href="{% url 'book:edit' book.id %}" class="mt-6 py-4 px-6 inline-block bg-sky-700 text-white">Edit</a>
    <a href="{% url 'book:delete' book.id %}" class="mt-6 py-4 px-6 inline-block bg-amber-700 text-white">Delete</a>
{% endblock %}

readr/book/templates/book/edit.html
{% extends 'core/base.html' %}

{% block title %}Edit book{% endblock %}

{% block content %}
    <h1 class="text-2xl">Edit book</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-4 px-6 bg-sky-700 text-white">Save changes</button>
    </form>
{% endblock %}

readr/book/templates/book/index.html
{% extends 'core/base.html' %}

{% block title %}Books{% endblock %}

{% block content %}
    <h1 class="mb-6 text-2xl">Books</h1>

    {% if books%}
        {% for book in books %}
            <div class="p-4 grid grid-cols-2 gap-4 bg-slate-100">
                <h2>
                    <a href="{% url 'book:detail' book.id %}">{{ book.title }}</a>
                </h2>

                <p>{{ book.get_status_display }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p>You don't have any books yet...</p>
    {% endif %}
{% endblock %}

readr/core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        
        {% load static %}
        

        <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %} 

        <style>
            footer{
                display: flexbox;
                padding: auto;
                text-align: center;
                margin-top: 600px;

            }
        </style>
    </head>

    <body>
        <nav class="max-w-4xl mx-auto py-6 px-8 flex justify-between items-center bg-slate-800">
            <a href="/" class="text-2xl text-white">Readr</a>

            

            <div class="space-x-6">
                <body class="bg-green-100"></body>
                <a href="{% url 'author:index' %}" class="text-white">Authors</a>
                <a href="{% url 'book:index' %}" class="text-white">Books</a>
                

                
                
                <a href="{% url 'core:register' %}" class=" py-4 px-6 bg-sky-700 text-white">Sign Up</a>
                <!-- <a href="{% url 'book:add' %}", class="py-4 px-6 bg-sky-700 text-white">Add book</a> -->
            </div>
        </nav>

        <div class="max-w-4xl mx-auto py-6 px-8">

            {% block content %}
            {% endblock %}
        </div>
        <footer>
            Oleksandr Rubtsov & 2024
        </footer>
    </body>
</html>

readr/core/templates/core/home.html
{% extends "core/base.html" %}



{% block title %}Home{% endblock %}

{% block content %}

<br>
{% if user.is_authenticated %}
<div class="box">
    <a href="{% url 'book:add' %}" class="py-2 px-4 bg-sky-700 text-white">Add Book</a>
    <a href="{% url 'author:add' %}" class="py-2 px-4 bg-sky-700 text-white">Add Author</a> 
</div>


<br>


<br>
<form action="{% url 'logout' %}"  method="post">
    {% csrf_token %}
    <button type="submit" class="py-2 px-4 bg-sky-700 text-white">Log out</button>
</form>
{% else %}
<p>You are not logged in</p>
<div class="border-top pt-3">
    <a href="{% url 'core:login' %}" class="py-2 px-4 bg-sky-700 text-white">Login </a>
</div>

{% endif %}

{% endblock %}

readr/core/templates/core/index.html
{% extends 'core/base.html' %}